import { describe, it, expect } from "vitest";
import { parseConfigResponse, fallbackClaudeMd, defaultSettings } from "../parse.js";
import type { ScanResult } from "@claude-scout/core";

const mockScan: ScanResult = {
  projectName: "my-app",
  projectPath: "/tmp/my-app",
  technologies: [
    { name: "Next.js", category: "framework", version: "14.0.0", confidence: 1, detectedFrom: "package.json" },
    { name: "TypeScript", category: "language", confidence: 1, detectedFrom: "tsconfig.json" },
    { name: "Prisma", category: "orm", version: "5.0.0", confidence: 1, detectedFrom: "package.json" },
  ],
  packageManager: "pnpm",
  hasTypeScript: true,
  hasDocker: false,
  hasCi: true,
  monorepo: false,
  detectedAt: new Date(),
};

function validPayload() {
  return {
    claudeMd: "# my-app\n\nA test project.",
    settingsJson: { model: "claude-sonnet-4-6", permissions: { allow: ["Read"], deny: [] } },
    settingsLocalJson: { permissions: { allow: [], deny: [] } },
    commands: [{ path: "test.md", content: "Run tests" }],
    rules: [{ path: "git.md", content: "Always rebase" }],
    skills: [{ name: "add-feature", content: "---\nname: add-feature\n---\nContent here" }],
  };
}

// ─── parseConfigResponse ───────────────────────────────────────────────────────

describe("parseConfigResponse", () => {
  it("parses a complete valid JSON response", () => {
    const raw = JSON.stringify(validPayload());
    const config = parseConfigResponse(raw, mockScan);

    expect(config.claudeMd).toBe("# my-app\n\nA test project.");
    expect(config.commands).toHaveLength(1);
    expect(config.commands[0]?.path).toBe("test.md");
    expect(config.rules).toHaveLength(1);
    expect(config.rules[0]?.path).toBe("git.md");
    expect(config.skills).toHaveLength(1);
    expect(config.skills[0]?.name).toBe("add-feature");
  });

  it("strips ```json fences before parsing", () => {
    const raw = "```json\n" + JSON.stringify(validPayload()) + "\n```";
    const config = parseConfigResponse(raw, mockScan);
    expect(config.claudeMd).toContain("my-app");
  });

  it("strips plain ``` fences before parsing", () => {
    const raw = "```\n" + JSON.stringify(validPayload()) + "\n```";
    const config = parseConfigResponse(raw, mockScan);
    expect(config.claudeMd).toContain("my-app");
  });

  it("throws on invalid JSON with a helpful message", () => {
    expect(() => parseConfigResponse("not json at all { broken", mockScan)).toThrow(
      /Claude returned invalid JSON/,
    );
  });

  it("includes the first 500 chars of raw response in the error", () => {
    const raw = "GARBAGE".repeat(20);
    expect(() => parseConfigResponse(raw, mockScan)).toThrow(/GARBAGE/);
  });

  it("uses fallback claudeMd when field is missing", () => {
    const partial = { ...validPayload(), claudeMd: undefined };
    const raw = JSON.stringify(partial);
    const config = parseConfigResponse(raw, mockScan);
    expect(config.claudeMd).toContain("my-app");
    expect(config.claudeMd).toContain("Generated by create-claude-config");
  });

  it("uses default settingsJson when field is missing", () => {
    const partial = { ...validPayload(), settingsJson: undefined };
    const raw = JSON.stringify(partial);
    const config = parseConfigResponse(raw, mockScan);
    expect(config.settingsJson).toBeDefined();
  });

  it("uses empty arrays for missing commands/rules/skills", () => {
    const raw = JSON.stringify({ claudeMd: "# test" });
    const config = parseConfigResponse(raw, mockScan);
    expect(config.commands).toEqual([]);
    expect(config.rules).toEqual([]);
    expect(config.skills).toEqual([]);
  });

  it("filters out malformed commands that lack path or content", () => {
    const payload = {
      ...validPayload(),
      commands: [
        { path: "valid.md", content: "good" },
        { path: "missing-content" },       // no content
        { content: "missing-path" },        // no path
        null,                               // null entry
        "a string",                         // wrong type
      ],
    };
    const config = parseConfigResponse(JSON.stringify(payload), mockScan);
    expect(config.commands).toHaveLength(1);
    expect(config.commands[0]?.path).toBe("valid.md");
  });

  it("filters out malformed skills that lack name or content", () => {
    const payload = {
      ...validPayload(),
      skills: [
        { name: "valid-skill", content: "content" },
        { name: "missing-content" },
        { content: "missing-name" },
      ],
    };
    const config = parseConfigResponse(JSON.stringify(payload), mockScan);
    expect(config.skills).toHaveLength(1);
    expect(config.skills[0]?.name).toBe("valid-skill");
  });
});

// ─── fallbackClaudeMd ──────────────────────────────────────────────────────────

describe("fallbackClaudeMd", () => {
  it("includes the project name", () => {
    const md = fallbackClaudeMd(mockScan);
    expect(md).toContain("my-app");
  });
});

// ─── defaultSettings ───────────────────────────────────────────────────────────

describe("defaultSettings", () => {
  it("includes the detected package manager in allow list", () => {
    const settings = defaultSettings(mockScan) as {
      permissions: { allow: string[] };
    };
    expect(settings.permissions.allow).toContain("Bash(pnpm *)");
  });

  it("falls back to npm when packageManager is unknown", () => {
    const scan = { ...mockScan, packageManager: "unknown" as const };
    const settings = defaultSettings(scan) as { permissions: { allow: string[] } };
    expect(settings.permissions.allow).toContain("Bash(npm *)");
  });

  it("always includes git in the allow list", () => {
    const settings = defaultSettings(mockScan) as { permissions: { allow: string[] } };
    expect(settings.permissions.allow).toContain("Bash(git *)");
  });
});
