import type { ScanResult, GeneratedConfig, GeneratedFile, SkillFile } from "@claude-kit/core";

/**
 * Parse the raw text response from Claude into a GeneratedConfig.
 * Handles JSON wrapped in markdown fences.
 */
export function parseConfigResponse(raw: string, scan: ScanResult): GeneratedConfig {
  const jsonStr = extractJson(raw);

  let parsed: RawConfig;
  try {
    parsed = JSON.parse(jsonStr) as RawConfig;
  } catch {
    throw new Error(
      `Claude returned invalid JSON.\n\nRaw response (first 500 chars):\n${raw.slice(0, 500)}`
    );
  }

  return {
    claudeMd:          parsed.claudeMd         ?? fallbackClaudeMd(scan),
    settingsJson:      parsed.settingsJson     ?? defaultSettings(scan),
    settingsLocalJson: parsed.settingsLocalJson ?? { permissions: { allow: [], deny: [] } },
    commands:          (parsed.commands        ?? []).filter(isGeneratedFile),
    rules:             (parsed.rules           ?? []).filter(isGeneratedFile),
    skills:            (parsed.skills          ?? []).filter(isSkillFile),
  };
}

interface RawConfig {
  claudeMd?: string;
  settingsJson?: object;
  settingsLocalJson?: object;
  commands?: unknown[];
  rules?: unknown[];
  skills?: unknown[];
}

function isGeneratedFile(x: unknown): x is GeneratedFile {
  return typeof x === "object" && x !== null &&
    typeof (x as GeneratedFile).path === "string" &&
    typeof (x as GeneratedFile).content === "string";
}

function isSkillFile(x: unknown): x is SkillFile {
  return typeof x === "object" && x !== null &&
    typeof (x as SkillFile).name === "string" &&
    typeof (x as SkillFile).content === "string";
}

function extractJson(raw: string): string {
  const trimmed = raw.trim();

  // Find the first `{` and walk character-by-character, tracking string boundaries
  // and brace depth. This is robust against markdown code fences and other `}` chars
  // appearing inside string values.
  const start = trimmed.indexOf("{");
  if (start === -1) return trimmed;

  let depth = 0;
  let inString = false;
  let escape = false;

  for (let i = start; i < trimmed.length; i++) {
    const ch = trimmed[i];

    if (escape) { escape = false; continue; }
    if (ch === "\\" && inString) { escape = true; continue; }
    if (ch === '"') { inString = !inString; continue; }
    if (inString) continue;

    if (ch === "{") depth++;
    else if (ch === "}") {
      depth--;
      if (depth === 0) return trimmed.slice(start, i + 1);
    }
  }

  // No balanced object found — fall back to greedy slice so the JSON.parse error
  // surfaces something useful in the raw-response preview.
  const end = trimmed.lastIndexOf("}");
  if (end > start) return trimmed.slice(start, end + 1);
  return trimmed;
}

export function fallbackClaudeMd(scan: ScanResult): string {
  return `# ${scan.projectName}\n\nGenerated by create-claude-config.\n`;
}

export function defaultSettings(scan: ScanResult): object {
  const pm = scan.packageManager !== "unknown" ? scan.packageManager : "npm";
  return {
    model: "claude-sonnet-4-6",
    permissions: {
      allow: ["Read", "Edit", "Write", "Bash(git *)", `Bash(${pm} *)`],
      deny: [],
    },
    hooks: {},
    env: {},
  };
}
